# Generated by Django 3.1.4 on 2025-05-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatePet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工作犬名称')),
                ('age', models.PositiveIntegerField(verbose_name='年龄（月）')),
                ('breed', models.CharField(max_length=50, verbose_name='品种')),
                ('work_type', models.CharField(help_text='如导盲犬、搜救犬等', max_length=50, verbose_name='工作类型')),
                ('training_status', models.CharField(choices=[('in_progress', '训练中'), ('qualified', '已认证')], max_length=50, verbose_name='训练状态')),
                ('description', models.TextField(verbose_name='工作能力简介')),
                ('image', models.ImageField(upload_to='corporate_pets/', verbose_name='工作犬照片')),
            ],
        ),
    ]
