# Generated by Django 3.1.4 on 2025-05-29 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrust', '0001_initial'),
        ('about', '0002_corporatepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=50, verbose_name='申请人姓名')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('applicant_address', models.CharField(max_length=200, verbose_name='居住地址')),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrust.entrustapplication', verbose_name='关联宠物')),
            ],
        ),
    ]
