# Generated by Django 3.1.4 on 2025-05-29 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrustApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('pet_name', models.CharField(max_length=50, verbose_name='宠物名称')),
                ('pet_age', models.PositiveIntegerField(verbose_name='宠物年龄')),
                ('pet_species', models.CharField(max_length=50, verbose_name='宠物品种')),
                ('description', models.TextField(verbose_name='宠物描述')),
                ('pet_image', models.ImageField(upload_to='entrust_pets/', verbose_name='宠物图片')),
                ('application_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态')),
            ],
        ),
    ]
